import express from "express";
import cors from "cors";
import dotenv from "dotenv";
import bodyParser from "body-parser";

import savedJobsRouter from "./src/routes/savedjobsandinternships.js";
import serviceRequestRouter from "./src/routes/servicerequest.js";
import servicerequestinterview from "./src/routes/servicerequest_interview.js";
import servicerequestreferraljobs from "./src/routes/servicerequest_referraljobs.js";
import servicerequest_offcampusinfo from "./src/routes/servicerequest_offcampusinfo.js";
import servicerequest_offcampusregister from "./src/routes/servicerequest_offcampusregister.js";
import servicerequest_oncampusinfo from "./src/routes/servicerequest_oncampusinfo.js";
import servicerequest_oncampusregister from "./src/routes/servicerequest_oncampusregister.js";
import servicerequest_ondemandtraining from "./src/routes/servicerequest_ondemandtraining.js";
import servicerequest_oncampusplacement from "./src/routes/servicerequest_oncampusplacement.js";
import servicerequest_studenttraining from "./src/routes/servicerequest_studenttraining.js";
import studentroute from "./src/routes/student.route.js";
import application_to_admin from "./src/routes/application_to_admin.js";
import uploadResumeRoute from "./src/routes/uploadresume.js";
import offCampusApplicationRoutes from "./src/routes/jobmanagement.js";
import oncampus from "./src/routes/oncampus.js";
import manage_application from "./src/routes/manage_application.js";
import jobapplication from "./src/routes/jobapplication.js";
import registeroncampus from "./src/controllers/registeredcandidates_oncampusapplication.js";
import servicerequest from "./src/routes/servicerequest_company_workforcesolutions.js";
import employeetraining from "./src/routes/servicerequest_company_employeetraining.js";
import branding from "./src/routes/servicerequest_company_branding.js";
import employeerbranding from "./src/routes/servicerequest_company_employeerbranding.js";
import oncampushiring from "./src/routes/hiringchannels_oncampus.js";
import oncampusregister from "./src/routes/hiringchannels_oncampus_register.js";
import internship from "./src/routes/hiringchannels_postinternships.js";
import jobs from "./src/routes/hiringchannels_postjob.js";
import seminars from "./src/routes/servicerequest_college_seminars.js";
import requestinfo from "./src/routes/servicerequest_college_studenttraining_requestinfo.js";
import collegeoncampus from "./src/routes/servicerequest_college_oncampus.js";
import collegerequestinfo from "./src/routes/servicerequest_college_oncampusrequest.js";
import additionalinfo from "./src/routes/onboarding_additionalinfo.js";
import preferences from "./src/routes/onboarding_preferences.js";
import education from "./src/routes/onboarding_education.js";
import basicdetails from "./src/routes/onboarding_basicdetails.js";
import resume from "./src/routes/onboarding_resume.js";
import "./config/db.js";

dotenv.config();

const app = express();
const PORT = process.env.PORT || 8081;

app.use(cors());
app.use(bodyParser.json());

app.use("/api/rawrecruit", savedJobsRouter);
app.use("/api/rawrecruit", serviceRequestRouter);
app.use("/api/rawrecruit", servicerequestinterview);
app.use("/api/rawrecruit", servicerequestreferraljobs);
app.use("/api/rawrecruit", servicerequest_offcampusinfo);
app.use("/api/rawrecruit", servicerequest_offcampusregister);
app.use("/api/rawrecruit", servicerequest_oncampusinfo);
app.use("/api/rawrecruit", servicerequest_oncampusregister);
app.use("/api/rawrecruit", servicerequest_ondemandtraining);
app.use("/api/rawrecruit", servicerequest_oncampusplacement);
app.use("/api/rawrecruit", servicerequest_studenttraining);
app.use("/api/rawrecruit", studentroute);
app.use("/api/rawrecruit", application_to_admin);
app.use("/api/rawrecruit/resume", uploadResumeRoute);
// app.use("/api/rawrecruit", offCampusApplicationRoutes);
// app.use("/api/rawrecruit", oncampus);
app.use("/api/rawrecruit", manage_application);
app.use("/api/rawrecruit", jobapplication);
app.use("/api/rawrecruit", registeroncampus);
app.use("/api/rawrecruit", servicerequest);
app.use("/api/rawrecruit", employeetraining);
app.use("/api/rawrecruit", branding);
app.use("/api/rawrecruit", employeerbranding);
app.use("/api/rawrecruit", employeetraining);
app.use("/api/rawrecruit", oncampushiring);
app.use("/api/rawrecruit", oncampusregister);
app.use("/api/rawrecruit", internship);
app.use("/api/rawrecruit", jobs);
app.use("/api/rawrecruit", seminars);
// app.use("/api/rawrecruit", registration);
app.use("/api/rawrecruit", requestinfo);
app.use("/api/rawrecruit", collegeoncampus);
app.use("/api/rawrecruit", collegerequestinfo);
app.use("/api/rawrecruit", additionalinfo);
app.use("/api/rawrecruit", preferences);
app.use("/api/rawrecruit", education);
app.use("/api/rawrecruit", basicdetails);
app.use("/api/rawrecruit", resume);

app.listen(PORT, () => {
  console.log(`Server is up and running on PORT: ${PORT}`);
});
