const mockJobs = [
    {
      id: '1',
      title: 'Software Engineer',
      company: 'Codegram',
      location: 'Bengaluru',
      type: 'Full-time',
      remote: true,
      experience: '3-5 years',
      description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros elementum tristique.',
      aboutRole: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros elementum tristique. Duis cursus, mi quis viverra ornare, eros dolor interdum nulla, ut commodo diam libero vitae erat.',
      responsibilities: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros elementum tristique. Duis cursus, mi quis viverra ornare, eros dolor interdum nulla, ut commodo diam libero vitae erat. Aenean faucibus nibh et justo cursus id rutrum lorem imperdiet. Nunc ut sem vitae risus tristique posuere.',
      details: [
        { label: 'Role', value: 'Software Engineer' },
        { label: 'Department', value: 'Product Manufacturing & Engineering' },
        { label: 'Employment Type', value: 'Full-Time, Permanent' },
        { label: 'Salary Range', value: '$117,357 - $200,000' },
        { label: 'Work Mode', value: 'On-site' },
      ],
      education: [
        { degree: 'BS', field: 'Computer Science' },
        { degree: 'MS', field: 'Software Engineering' }
      ],
      skills: ['Node.js', 'React', 'Angular', 'PostgreSQL', 'Python', 'MongoDB'],
      timeAgo: '14h',
      postedDate: '2025-05-01T10:00:00Z',
      aboutCompany: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros elementum tristique. Duis cursus, mi quis viverra ornare, eros dolor interdum nulla, ut commodo diam libero vitae erat.',
      companyInfo: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros elementum tristique.',
      category: 'Engineering'
    },
    {
      id: '2',
      title: 'Frontend Developer',
      company: 'WebSolutions',
      location: 'Hyderabad',
      type: 'Full-time',
      remote: true,
      experience: '2-4 years',
      description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros elementum tristique.',
      aboutRole: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros elementum tristique. Duis cursus, mi quis viverra ornare, eros dolor interdum nulla, ut commodo diam libero vitae erat.',
      responsibilities: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros elementum tristique. Duis cursus, mi quis viverra ornare, eros dolor interdum nulla, ut commodo diam libero vitae erat. Aenean faucibus nibh et justo cursus id rutrum lorem imperdiet. Nunc ut sem vitae risus tristique posuere.',
      skills: ['React', 'JavaScript', 'HTML', 'CSS', 'Tailwind CSS'],
      timeAgo: '14h',
      postedDate: '2025-05-02T09:30:00Z',
      aboutCompany: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros elementum tristique. Duis cursus, mi quis viverra ornare, eros dolor interdum nulla, ut commodo diam libero vitae erat.',
      category: 'Engineering'
    },
    {
      id: '3',
      title: 'Product Manager',
      company: 'TechStack',
      location: 'Mumbai',
      type: 'Full-time',
      remote: false,
      experience: '5+ years',
      description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros elementum tristique.',
      aboutRole: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros elementum tristique. Duis cursus, mi quis viverra ornare, eros dolor interdum nulla, ut commodo diam libero vitae erat.',
      responsibilities: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros elementum tristique. Duis cursus, mi quis viverra ornare, eros dolor interdum nulla, ut commodo diam libero vitae erat. Aenean faucibus nibh et justo cursus id rutrum lorem imperdiet. Nunc ut sem vitae risus tristique posuere.',
      skills: ['Product Development', 'Agile', 'User Research', 'Roadmapping'],
      timeAgo: '14h',
      postedDate: '2025-05-03T08:45:00Z',
      aboutCompany: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros elementum tristique. Duis cursus, mi quis viverra ornare, eros dolor interdum nulla, ut commodo diam libero vitae erat.',
      category: 'Product'
    },
    {
      id: '4',
      title: 'Data Scientist',
      company: 'DataInsights',
      location: 'Pune',
      type: 'Full-time',
      remote: true,
      experience: '3-6 years',
      description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros elementum tristique.',
      aboutRole: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros elementum tristique. Duis cursus, mi quis viverra ornare, eros dolor interdum nulla, ut commodo diam libero vitae erat.',
      responsibilities: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros elementum tristique. Duis cursus, mi quis viverra ornare, eros dolor interdum nulla, ut commodo diam libero vitae erat. Aenean faucibus nibh et justo cursus id rutrum lorem imperdiet. Nunc ut sem vitae risus tristique posuere.',
      skills: ['Python', 'Machine Learning', 'SQL', 'Data Visualization', 'Statistics'],
      timeAgo: '14h',
      postedDate: '2025-05-04T11:15:00Z',
      aboutCompany: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros elementum tristique. Duis cursus, mi quis viverra ornare, eros dolor interdum nulla, ut commodo diam libero vitae erat.',
      category: 'Data Science'
    },
    {
      id: '5',
      title: 'UX/UI Designer',
      company: 'DesignStudio',
      location: 'Bangalore',
      type: 'Full-time',
      remote: true,
      experience: '2-5 years',
      description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros elementum tristique.',
      aboutRole: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros elementum tristique. Duis cursus, mi quis viverra ornare, eros dolor interdum nulla, ut commodo diam libero vitae erat.',
      responsibilities: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros elementum tristique. Duis cursus, mi quis viverra ornare, eros dolor interdum nulla, ut commodo diam libero vitae erat. Aenean faucibus nibh et justo cursus id rutrum lorem imperdiet. Nunc ut sem vitae risus tristique posuere.',
      skills: ['Figma', 'Adobe XD', 'User Research', 'Wireframing', 'Prototyping'],
      timeAgo: '14h',
      postedDate: '2025-05-04T14:30:00Z',
      aboutCompany: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros elementum tristique. Duis cursus, mi quis viverra ornare, eros dolor interdum nulla, ut commodo diam libero vitae erat.',
      category: 'Design'
    },
    {
      id: '6',
      title: 'DevOps Engineer',
      company: 'CloudTech',
      location: 'Noida',
      type: 'Full-time',
      remote: true,
      experience: '4-7 years',
      description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros elementum tristique.',
      aboutRole: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros elementum tristique. Duis cursus, mi quis viverra ornare, eros dolor interdum nulla, ut commodo diam libero vitae erat.',
      responsibilities: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros elementum tristique. Duis cursus, mi quis viverra ornare, eros dolor interdum nulla, ut commodo diam libero vitae erat. Aenean faucibus nibh et justo cursus id rutrum lorem imperdiet. Nunc ut sem vitae risus tristique posuere.',
      skills: ['AWS', 'Docker', 'Kubernetes', 'CI/CD', 'Terraform', 'Linux'],
      timeAgo: '14h',
      postedDate: '2025-05-05T09:00:00Z',
      aboutCompany: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros elementum tristique. Duis cursus, mi quis viverra ornare, eros dolor interdum nulla, ut commodo diam libero vitae erat.',
      category: 'Engineering'
    },
    {
      id: '7',
      title: 'Backend Developer',
      company: 'ServerSide',
      location: 'Delhi',
      type: 'Full-time',
      remote: true,
      experience: '3-5 years',
      description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros elementum tristique.',
      skills: ['Node.js', 'Express', 'MongoDB', 'PostgreSQL', 'Redis'],
      timeAgo: '14h',
      postedDate: '2025-05-05T10:45:00Z',
      category: 'Engineering'
    },
    {
      id: '8',
      title: 'Marketing Specialist',
      company: 'BrandBoost',
      location: 'Mumbai',
      type: 'Full-time',
      remote: false,
      experience: '2-4 years',
      description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros elementum tristique.',
      aboutRole: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros elementum tristique. Duis cursus, mi quis viverra ornare, eros dolor interdum nulla, ut commodo diam libero vitae erat.',
      responsibilities: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros elementum tristique. Duis cursus, mi quis viverra ornare, eros dolor interdum nulla, ut commodo diam libero vitae erat. Aenean faucibus nibh et justo cursus id rutrum lorem imperdiet. Nunc ut sem vitae risus tristique posuere.',
      skills: ['Digital Marketing', 'SEO', 'Content Creation', 'Social Media', 'Analytics'],
      timeAgo: '14h',
      postedDate: '2025-05-05T13:20:00Z',
      aboutCompany: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros elementum tristique. Duis cursus, mi quis viverra ornare, eros dolor interdum nulla, ut commodo diam libero vitae erat.',
      category: 'Marketing'
    },   {
        id: '8',
        title: 'Marketing Specialist',
        company: 'BrandBoost',
        location: 'Mumbai',
        type: 'Full-time',
        remote: false,
        experience: '2-4 years',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros elementum tristique.',
        aboutRole: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros elementum tristique. Duis cursus, mi quis viverra ornare, eros dolor interdum nulla, ut commodo diam libero vitae erat.',
        responsibilities: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros elementum tristique. Duis cursus, mi quis viverra ornare, eros dolor interdum nulla, ut commodo diam libero vitae erat. Aenean faucibus nibh et justo cursus id rutrum lorem imperdiet. Nunc ut sem vitae risus tristique posuere.',
        skills: ['Digital Marketing', 'SEO', 'Content Creation', 'Social Media', 'Analytics'],
        timeAgo: '14h',
        postedDate: '2025-05-05T13:20:00Z',
        aboutCompany: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros elementum tristique. Duis cursus, mi quis viverra ornare, eros dolor interdum nulla, ut commodo diam libero vitae erat.',
        category: 'Marketing'
      },   {
        id: '8',
        title: 'Marketing Specialist',
        company: 'BrandBoost',
        location: 'Mumbai',
        type: 'Full-time',
        remote: false,
        experience: '2-4 years',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros elementum tristique.',
        aboutRole: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros elementum tristique. Duis cursus, mi quis viverra ornare, eros dolor interdum nulla, ut commodo diam libero vitae erat.',
        responsibilities: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros elementum tristique. Duis cursus, mi quis viverra ornare, eros dolor interdum nulla, ut commodo diam libero vitae erat. Aenean faucibus nibh et justo cursus id rutrum lorem imperdiet. Nunc ut sem vitae risus tristique posuere.',
        skills: ['Digital Marketing', 'SEO', 'Content Creation', 'Social Media', 'Analytics'],
        timeAgo: '14h',
        postedDate: '2025-05-05T13:20:00Z',
        aboutCompany: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros elementum tristique. Duis cursus, mi quis viverra ornare, eros dolor interdum nulla, ut commodo diam libero vitae erat.',
        category: 'Marketing'
      },   {
        id: '8',
        title: 'Marketing Specialist',
        company: 'BrandBoost',
        location: 'Mumbai',
        type: 'Full-time',
        remote: false,
        experience: '2-4 years',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros elementum tristique.',
        aboutRole: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros elementum tristique. Duis cursus, mi quis viverra ornare, eros dolor interdum nulla, ut commodo diam libero vitae erat.',
        responsibilities: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros elementum tristique. Duis cursus, mi quis viverra ornare, eros dolor interdum nulla, ut commodo diam libero vitae erat. Aenean faucibus nibh et justo cursus id rutrum lorem imperdiet. Nunc ut sem vitae risus tristique posuere.',
        skills: ['Digital Marketing', 'SEO', 'Content Creation', 'Social Media', 'Analytics'],
        timeAgo: '14h',
        postedDate: '2025-05-05T13:20:00Z',
        aboutCompany: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros elementum tristique. Duis cursus, mi quis viverra ornare, eros dolor interdum nulla, ut commodo diam libero vitae erat.',
        category: 'Marketing'
      },   {
        id: '8',
        title: 'Marketing Specialist',
        company: 'BrandBoost',
        location: 'Mumbai',
        type: 'Full-time',
        remote: false,
        experience: '2-4 years',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros elementum tristique.',
        aboutRole: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros elementum tristique. Duis cursus, mi quis viverra ornare, eros dolor interdum nulla, ut commodo diam libero vitae erat.',
        responsibilities: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros elementum tristique. Duis cursus, mi quis viverra ornare, eros dolor interdum nulla, ut commodo diam libero vitae erat. Aenean faucibus nibh et justo cursus id rutrum lorem imperdiet. Nunc ut sem vitae risus tristique posuere.',
        skills: ['Digital Marketing', 'SEO', 'Content Creation', 'Social Media', 'Analytics'],
        timeAgo: '14h',
        postedDate: '2025-05-05T13:20:00Z',
        aboutCompany: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros elementum tristique. Duis cursus, mi quis viverra ornare, eros dolor interdum nulla, ut commodo diam libero vitae erat.',
        category: 'Marketing'
      },   {
        id: '8',
        title: 'Marketing Specialist',
        company: 'BrandBoost',
        location: 'Mumbai',
        type: 'Full-time',
        remote: false,
        experience: '2-4 years',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros elementum tristique.',
        aboutRole: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros elementum tristique. Duis cursus, mi quis viverra ornare, eros dolor interdum nulla, ut commodo diam libero vitae erat.',
        responsibilities: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros elementum tristique. Duis cursus, mi quis viverra ornare, eros dolor interdum nulla, ut commodo diam libero vitae erat. Aenean faucibus nibh et justo cursus id rutrum lorem imperdiet. Nunc ut sem vitae risus tristique posuere.',
        skills: ['Digital Marketing', 'SEO', 'Content Creation', 'Social Media', 'Analytics'],
        timeAgo: '14h',
        postedDate: '2025-05-05T13:20:00Z',
        aboutCompany: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros elementum tristique. Duis cursus, mi quis viverra ornare, eros dolor interdum nulla, ut commodo diam libero vitae erat.',
        category: 'Marketing'
      },   {
        id: '8',
        title: 'Marketing Specialist',
        company: 'BrandBoost',
        location: 'Mumbai',
        type: 'Full-time',
        remote: false,
        experience: '2-4 years',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros elementum tristique.',
        aboutRole: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros elementum tristique. Duis cursus, mi quis viverra ornare, eros dolor interdum nulla, ut commodo diam libero vitae erat.',
        responsibilities: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros elementum tristique. Duis cursus, mi quis viverra ornare, eros dolor interdum nulla, ut commodo diam libero vitae erat. Aenean faucibus nibh et justo cursus id rutrum lorem imperdiet. Nunc ut sem vitae risus tristique posuere.',
        skills: ['Digital Marketing', 'SEO', 'Content Creation', 'Social Media', 'Analytics'],
        timeAgo: '14h',
        postedDate: '2025-05-05T13:20:00Z',
        aboutCompany: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros elementum tristique. Duis cursus, mi quis viverra ornare, eros dolor interdum nulla, ut commodo diam libero vitae erat.',
        category: 'Marketing'
      },   {
        id: '8',
        title: 'Marketing Specialist',
        company: 'BrandBoost',
        location: 'Mumbai',
        type: 'Full-time',
        remote: false,
        experience: '2-4 years',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros elementum tristique.',
        aboutRole: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros elementum tristique. Duis cursus, mi quis viverra ornare, eros dolor interdum nulla, ut commodo diam libero vitae erat.',
        responsibilities: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros elementum tristique. Duis cursus, mi quis viverra ornare, eros dolor interdum nulla, ut commodo diam libero vitae erat. Aenean faucibus nibh et justo cursus id rutrum lorem imperdiet. Nunc ut sem vitae risus tristique posuere.',
        skills: ['Digital Marketing', 'SEO', 'Content Creation', 'Social Media', 'Analytics'],
        timeAgo: '14h',
        postedDate: '2025-05-05T13:20:00Z',
        aboutCompany: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros elementum tristique. Duis cursus, mi quis viverra ornare, eros dolor interdum nulla, ut commodo diam libero vitae erat.',
        category: 'Marketing'
      },
];

export default function fetchJobs() {
    return Promise.resolve(mockJobs);
  }
  