const dummyCandidates = [
  {
    id: 1,
    name: "Aarav Sharma",
    location: "Bengaluru, India",
    currentSalary: 1200000,
    expectedSalary: 1500000,
    email: "aarav.sharma@example.com",
    phone: "+91 9876543210",
    linkedin: "https://linkedin.com/in/aarav-sharma",
    github: "https://github.com/aaravsharma",
    portfolio: "https://aarav-portfolio.com",
    cv: "https://example.com/cv/aarav-sharma.pdf",
    education: "B.Tech in Computer Science",
    experience: 3,
    languages: ["English", "Hindi"],
    gender: "Male",
    age: 26,
    designation: "Frontend Developer",
    industry: "Information Technology",
    skills: ["React", "TypeScript", "TailwindCSS", "Node.js", "MongoDB"],
    shortlisted: false,

    // required for filters
    status: "active",
    postedBy: "me",
    appliedDate: "2025-09-12",
  },
  {
    id: 2,
    name: "Priya Verma",
    location: "Hyderabad, India",
    currentSalary: 800000,
    expectedSalary: 1000000,
    email: "priya.verma@example.com",
    phone: "+91 9123456789",
    linkedin: "https://linkedin.com/in/priya-verma",
    github: "https://github.com/priyaverma",
    portfolio: null,
    cv: "https://example.com/cv/priya-verma.pdf",
    education: "MCA",
    experience: 5,
    languages: ["English", "Telugu", "Hindi"],
    gender: "Female",
    age: 29,
    designation: "Backend Engineer",
    industry: "FinTech",
    skills: ["Java", "Spring Boot", "MySQL", "Kafka", "Docker"],
    shortlisted: true,

    status: "expired",
    postedBy: "user2",
    appliedDate: "2025-09-10",
  },
  {
    id: 3,
    name: "Rohit Patel",
    location: "Pune, India",
    currentSalary: 600000,
    expectedSalary: 850000,
    email: "rohit.patel@example.com",
    phone: "+91 9988776655",
    linkedin: "https://linkedin.com/in/rohit-patel",
    github: null,
    portfolio: null,
    cv: "https://example.com/cv/rohit-patel.pdf",
    education: "B.Sc IT",
    experience: 2,
    languages: ["English", "Gujarati", "Hindi"],
    gender: "Male",
    age: 24,
    designation: "Junior Developer",
    industry: "E-commerce",
    skills: ["JavaScript", "HTML", "CSS", "React"],
    shortlisted: false,

    status: "active",
    postedBy: "user3",
    appliedDate: "2025-09-08",
  },
];

export default dummyCandidates;
